-- Missing hotfix parent rows from DBErrors.log + Wowhead names. Does not delete.
SET NAMES utf8mb4;

-- NPCText BroadcastText parents
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',311350,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',313509,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',313788,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',313963,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',313967,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',313968,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',314128,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',315204,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',315212,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',315868,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',317701,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',317809,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',317811,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',318200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',320315,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`broadcast_text` (`Text`,`Text1`,`ID`,`LanguageID`,`ConditionID`,`EmotesID`,`Flags`,`ChatBubbleDurationMs`,`VoiceOverPriorityID`,`SoundKitID1`,`SoundKitID2`,`EmoteID1`,`EmoteID2`,`EmoteID3`,`EmoteDelay1`,`EmoteDelay2`,`EmoteDelay3`,`VerifiedBuild`) VALUES ('','',322883,0,0,0,0,0,0,0,0,0,0,0,0,0,0,68974);

-- CreatureDisplayInfo clones (model from 140993 if present, else newest)
INSERT IGNORE INTO `hotfixes`.`creature_display_info` (`ID`,`ModelID`,`SoundID`,`SizeClass`,`CreatureModelScale`,`CreatureModelAlpha`,`BloodID`,`ExtendedDisplayInfoID`,`NPCSoundID`,`ParticleColorID`,`PortraitCreatureDisplayInfoID`,`PortraitTextureFileDataID`,`ObjectEffectPackageID`,`AnimReplacementSetID`,`Flags`,`StateSpellVisualKitID`,`PlayerOverrideScale`,`PetInstanceScale`,`UnarmedWeaponType`,`MountPoofSpellVisualKitID`,`DissolveEffectID`,`Gender`,`DissolveOutEffectID`,`CreatureModelMinLod`,`ConditionalCreatureModelID`,`Unknown_1100_1`,`Unknown_1100_2`,`TextureVariationFileDataID1`,`TextureVariationFileDataID2`,`TextureVariationFileDataID3`,`TextureVariationFileDataID4`,`VerifiedBuild`)
SELECT d.`new_id`, s.`ModelID`, s.`SoundID`, s.`SizeClass`, s.`CreatureModelScale`, s.`CreatureModelAlpha`, s.`BloodID`, s.`ExtendedDisplayInfoID`, s.`NPCSoundID`, s.`ParticleColorID`, s.`PortraitCreatureDisplayInfoID`, s.`PortraitTextureFileDataID`, s.`ObjectEffectPackageID`, s.`AnimReplacementSetID`, s.`Flags`, s.`StateSpellVisualKitID`, s.`PlayerOverrideScale`, s.`PetInstanceScale`, s.`UnarmedWeaponType`, s.`MountPoofSpellVisualKitID`, s.`DissolveEffectID`, s.`Gender`, s.`DissolveOutEffectID`, s.`CreatureModelMinLod`, s.`ConditionalCreatureModelID`, s.`Unknown_1100_1`, s.`Unknown_1100_2`, s.`TextureVariationFileDataID1`, s.`TextureVariationFileDataID2`, s.`TextureVariationFileDataID3`, s.`TextureVariationFileDataID4`, 68974 FROM (SELECT 68974 AS dummy) _ JOIN (SELECT * FROM `hotfixes`.`creature_display_info`       WHERE `ID`=140993 OR `ID`=(SELECT MAX(`ID`) FROM `hotfixes`.`creature_display_info`)       ORDER BY `ID`=140993 DESC LIMIT 1) s JOIN (SELECT 140387 AS new_id UNION SELECT 140390 AS new_id UNION SELECT 140951 AS new_id UNION SELECT 140952 AS new_id UNION SELECT 140955 AS new_id UNION SELECT 140971 AS new_id UNION SELECT 141319 AS new_id UNION SELECT 141423 AS new_id UNION SELECT 144546 AS new_id UNION SELECT 144823 AS new_id UNION SELECT 144824 AS new_id UNION SELECT 144872 AS new_id UNION SELECT 145875 AS new_id) d;

-- Missing items (item + item_sparse)
INSERT IGNORE INTO `hotfixes`.`item` (`ID`,`ClassID`,`SubclassID`,`Material`,`InventoryType`,`SheatheType`,`SoundOverrideSubclassID`,`IconFileDataID`,`ItemGroupSoundsID`,`ContentTuningID`,`ModifiedCraftingReagentItemID`,`Unknown1200`,`CraftingQualityID`,`ItemSquishEraID`,`RecraftReagentCountPercentage`,`OrderSource`,`VerifiedBuild`) VALUES (265039,15,0,0,0,0,-1,133661,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`item_sparse` (`ID`,`Display`,`ExpansionID`,`Stackable`,`MaxCount`,`ItemLevel`,`AllowableClass`,`OverallQualityID`,`Bonding`,`RequiredLevel`,`VerifiedBuild`) VALUES (265039,'Missing Item 265039',11,20,0,1,-1,1,1,1,68974);
INSERT IGNORE INTO `hotfixes`.`item` (`ID`,`ClassID`,`SubclassID`,`Material`,`InventoryType`,`SheatheType`,`SoundOverrideSubclassID`,`IconFileDataID`,`ItemGroupSoundsID`,`ContentTuningID`,`ModifiedCraftingReagentItemID`,`Unknown1200`,`CraftingQualityID`,`ItemSquishEraID`,`RecraftReagentCountPercentage`,`OrderSource`,`VerifiedBuild`) VALUES (276910,15,0,0,0,0,-1,133661,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`item_sparse` (`ID`,`Display`,`ExpansionID`,`Stackable`,`MaxCount`,`ItemLevel`,`AllowableClass`,`OverallQualityID`,`Bonding`,`RequiredLevel`,`VerifiedBuild`) VALUES (276910,'Missing Item 276910',11,20,0,1,-1,1,1,1,68974);
INSERT IGNORE INTO `hotfixes`.`item` (`ID`,`ClassID`,`SubclassID`,`Material`,`InventoryType`,`SheatheType`,`SoundOverrideSubclassID`,`IconFileDataID`,`ItemGroupSoundsID`,`ContentTuningID`,`ModifiedCraftingReagentItemID`,`Unknown1200`,`CraftingQualityID`,`ItemSquishEraID`,`RecraftReagentCountPercentage`,`OrderSource`,`VerifiedBuild`) VALUES (276911,15,0,0,0,0,-1,133661,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`item_sparse` (`ID`,`Display`,`ExpansionID`,`Stackable`,`MaxCount`,`ItemLevel`,`AllowableClass`,`OverallQualityID`,`Bonding`,`RequiredLevel`,`VerifiedBuild`) VALUES (276911,'Missing Item 276911',11,20,0,1,-1,1,1,1,68974);
INSERT IGNORE INTO `hotfixes`.`item` (`ID`,`ClassID`,`SubclassID`,`Material`,`InventoryType`,`SheatheType`,`SoundOverrideSubclassID`,`IconFileDataID`,`ItemGroupSoundsID`,`ContentTuningID`,`ModifiedCraftingReagentItemID`,`Unknown1200`,`CraftingQualityID`,`ItemSquishEraID`,`RecraftReagentCountPercentage`,`OrderSource`,`VerifiedBuild`) VALUES (276913,15,0,0,0,0,-1,133661,0,0,0,0,0,0,0,0,68974);
INSERT IGNORE INTO `hotfixes`.`item_sparse` (`ID`,`Display`,`ExpansionID`,`Stackable`,`MaxCount`,`ItemLevel`,`AllowableClass`,`OverallQualityID`,`Bonding`,`RequiredLevel`,`VerifiedBuild`) VALUES (276913,'Missing Item 276913',11,20,0,1,-1,1,1,1,68974);

